### ISSUE TITLE
BMC swu releases missing ?

### ISSUE THREAD

**Issue by clem2k** [wenyi0421/turing-pi#1]
Hi, I couldn't find any release for the BMC update. As my board comes with no root access i'd like to update it but could not find any swu file in the repo, can you help me please ?

**Comment by depasseg** [comment]
Same.   Was directed here from https://help.turingpi.com/hc/en-us/articles/8686945524893-Baseboard-Management-Controller-BMC-#f179cf73

**Comment by michaelschapira** [comment]
I had the same issue. 
for now, you can connect an usb cable from the tpi board (mini usb, bmc) to your computer and use `adb shell` to get a shell. 
adb comes from android sdk:  https://developer.android.com/studio/command-line/adb

from there, you can update sshd_config to allow root access. 
I'll get better doc there when on a computer.

**Comment by smeee-again** [comment]
> Hi, I couldn't find any release for the BMC update. As my board comes with no root access i'd like to update it but could not find any swu file in the repo, can you help me please ?

That is because it hasn't been released yet.  There is an ***upcoming*** update.  We would all like to update the BMC but we all have to wait for the upcoming release to be released.

**Comment by clem2k** [comment]
Thanks for the info. So let's be patient 😅

**Comment by daniel-gallagher** [comment]
I think the docs just point to the incorrect repo. There is firmware [HERE](https://github.com/wenyi0421/turingpi-fw/releases/tag/v1.0.0) in their other repo. I am not sure if it is the most recent code, but it does work to reflash the BMC.

**Comment by smeee-again** [comment]
The date is from Nov 16, 2022 and it is v1.0.0.

**Comment by daniel-gallagher** [comment]
> The date is from Nov 16, 2022 and it is v1.0.0.

Correct. I guess I should have been more clear. If there is not a more recent release, then this would be the most current swu available. Unless the boards are shipped with newer code (which I suspect might be the case) and that is what I meant by not knowing if it was the most recent code. It will allow though for reflashing in an emergency if needed. 

I am away from my board, but I believe the version loaded is `1.0.0.7` which would mean it is either newer than that swu, or the last digit was omitted by accident.

**Comment by sachasmart** [comment]
Blows my mind that this board can't even detect the nodes out of the box. For the price, this is extremely disappointing.

**Comment by smeee-again** [comment]
> Blows my mind that this board can't even detect the nodes out of the box. For the price, this is extremely disappointing.

The Turing Pi v2 board was never going to be a huge seller, it is not like a standard desktop computer that say Dell expects to sell a lot of.  It is more of a niche market and the price to value will always be low for niche products.  How exactly are they going to accurately detect what the node is?  It is not like when the Raspberry Pi Foundation designed the CM4 that they thought they should include capabilities for third-parties to detect their modules.  Even if they did, what about Nvidia?  Would they follow the same specification as the CM4 even though the board connection is nothing like the CM4?  Could Turing Pi have added something to the adapter board?  Sure, but then what?  All it could provide is that it is either a CM4 or something that has the same compatibility and thus could be used with the board.  There are other modules that people have used on the adapter board that are not CM4's.

**Comment by smithrb** [comment]
Not having any luck building on my setup.  I did incorporate the deltas pushed by rayrrr, but I'm getting build errors related to "Cannot execute cross-compiler '/home/smithb/turing-pi/buildroot/output/host/opt/ext-toolchain/bin/arm-linux-gnueabi-gcc'".  So, it's not clear to me what the build environment should be.  I'm on 64-bit bullseye - latest and fully up to date.
