### ISSUE TITLE
Jetson Nano does not boot.

### ISSUE THREAD

**Issue by charlieporth1** [wenyi0421/turing-pi#10]
Jetson Nano does not boot. I've checked serial output. Ethernet Leds are not going on. Red power leds are on. No output from serial. No output from node 3 via HDMI

**Comment by wenyi0421** [comment]
Please burn the firmware in jetson Nano, you can use the official backplane to verify whether it can be started. Only node1 can connect to HDMI

**Comment by charlieporth1** [comment]
If you don't mind pointing me in the right direction of the firmware that would be great. I have an sdcard already in the nano & flashed. I also saw mention of the B01 variant is the only one that works. I have the A02 could that be the problem?

**Comment by wenyi0421** [comment]
yes you should use B01
