### ISSUE TITLE
Default hostname

### ISSUE THREAD

**Issue by ShigeakiAsai** [wenyi0421/turing-pi#19]
BMC version : 1.0.1

The hostname command returns "turing".
But, there is "turing pi" in /etc/hostname. 

![BMC-HOSTNAME](https://user-images.githubusercontent.com/83913986/236846692-b0d88445-add7-4eeb-b136-e4b6832121a0.png)

I hope that hostname is changed  somthing good one :)

Thanks, ASAI

**Comment by rbakbashev** [comment]
Fixed in turing-machines/turing-pi#39. Sorry for the lack of imagination :-)

**Comment by ShigeakiAsai** [comment]
Hello @ruslashev

Thank you for your information.
I will close this issue when I confirm it in next release!

\> Sorry for the lack of imagination :-)
If I were you, I would take the same name! (^_^)b

Thanks, ASAI

**Comment by ShigeakiAsai** [comment]
Sorry for my mis operation.

**Comment by ShigeakiAsai** [comment]
I confirmed to fix this issue on bmc version 1.0.2.

Thanks, ASAI
