### ISSUE TITLE
make V=1 failed with cjson.h missing

### ISSUE THREAD

**Issue by cooling75** [wenyi0421/turing-pi#2]
Hi,
I tried to follow the README but ended up with this error on the second step:

```bash
make[1]: *** [<builtin>: param.o] Error 1
make[1]: *** Waiting for unfinished jobs....
webserver.c:15:10: fatal error: cjson/cJSON.h: No such file or directory
 #include "cjson/cJSON.h"
          ^~~~~~~~~~~~~~~
```

**Comment by andreaspeters** [comment]
Same here. Even after I installed "libcjson-dev".

**Comment by dougbertwashere** [comment]
to repeat the obvious, ditto

**Comment by rayrrr** [comment]
That worked for me, thanks @wenyi0421. I recommend updating the build directions to include this step.

**Comment by sachasmart-weavik** [comment]
These docs should also be updated: https://help.turingpi.com/hc/en-us/articles/8687025578269-BMC-Firmware-build-and-modify
