### ISSUE TITLE
turingpi-1.0.1.swu update on turing-pi 2 without sdcard

### ISSUE THREAD

**Issue by akrami** [wenyi0421/turing-pi#8]
I try to install version 1.0.1 on my turing-pi v2 but it keeps returning this error:
```
Content-Type: text/plain
{"response":[{"result":"err:no sdcard"}]}
```

**Comment by wenyi0421** [comment]
You need to insert sd card to install

**Comment by akrami** [comment]
sd-card where? for what?

**Comment by wenyi0421** [comment]
The TF card slot is located on the back of the board, and the upgrade file will be first uploaded to the card for the upgrade process. This is done to prevent potential upgrade failures that may occur when dealing with large files.

**Comment by akrami** [comment]
Thank you
Please update the documentation regarding the need of SD Card.
